/*
 * MainForm.java
 *
 * Created on March 2, 2007, 9:16 PM
 */

package com.totsp.desklet.rome;

import java.awt.Color;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import org.jdesktop.swingx.JXPanel;
import org.jdesktop.swingx.painter.ImagePainter;
import org.xhtmlrenderer.simple.XHTMLPanel;

/**
 *
 * @author  cooper
 */
public class MainForm extends JXPanel {
    BufferedImage background;
    XHTMLPanel display = new XHTMLPanel();
    /** Creates new form MainForm */
    public MainForm() {
        try{
            background = ImageIO.read( getClass().getResource("/com/totsp/desklet/rome/Background.png"));
        } catch(Exception e){
            e.printStackTrace();
        }
        this.setBackgroundPainter(new ImagePainter( background ));
        initComponents();
        display.setOpaque( false );
        display.setDocument( getClass().getResource("/com/totsp/desklet/rome/temp.xml").toExternalForm());
        display.setForeground( Color.WHITE );
        this.jPanel1.add( display );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        now = new javax.swing.JLabel();
        now1 = new javax.swing.JLabel();
        now2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        browse = new javax.swing.JButton();
        feed = new javax.swing.JButton();
        back = new javax.swing.JButton();
        pause = new javax.swing.JButton();
        forward = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(325, 450));
        setMinimumSize(new java.awt.Dimension(325, 450));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/totsp/desklet/rome/romepower02-tiny.png"))); // NOI18N

        now.setForeground(new java.awt.Color(255, 255, 255));
        now.setText("current");

        now1.setForeground(new java.awt.Color(153, 153, 153));
        now1.setText("prev");

        now2.setForeground(new java.awt.Color(51, 51, 51));
        now2.setText("prevprev");

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        browse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/totsp/desklet/rome/browse.gif"))); // NOI18N
        browse.setOpaque(false);

        feed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/totsp/desklet/rome/rssicon.png"))); // NOI18N
        feed.setOpaque(false);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/totsp/desklet/rome/backward.png"))); // NOI18N
        back.setOpaque(false);

        pause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/totsp/desklet/rome/pause.png"))); // NOI18N
        pause.setOpaque(false);

        forward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/totsp/desklet/rome/forward.png"))); // NOI18N
        forward.setOpaque(false);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, now2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .add(now1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .add(now, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel1))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(back, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(pause, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(forward, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 88, Short.MAX_VALUE)
                        .add(feed, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(4, 4, 4)
                        .add(browse, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(jLabel1))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(now2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(now1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(now)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(browse)
                    .add(feed)
                    .add(forward, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(back, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pause, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton back;
    public javax.swing.JButton browse;
    public javax.swing.JButton feed;
    public javax.swing.JButton forward;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel now;
    public javax.swing.JLabel now1;
    public javax.swing.JLabel now2;
    public javax.swing.JButton pause;
    // End of variables declaration//GEN-END:variables
    
}
