/*
 * ConfigPanel.java
 *
 * Created on March 31, 2007, 8:40 AM
 */

package picoftheday;
import javax.swing.JComboBox;
import java.awt.event.*;
/**
 *
 * @author  jwill
 */
public class ConfigPanel extends javax.swing.JPanel {
    PhotoFeed oldSelected;
    /** Creates new form ConfigPanel */
    public ConfigPanel() {
        initComponents();
        try {
            oldSelected = PhotoFeed.getSelectedFeed();
        } catch(Exception ex) { }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtQuery = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        txtPage = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        sourcesComboBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        sourceTypeComboBox = new javax.swing.JComboBox();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel6.setText("Sources:");

        jLabel4.setText("Query/Xpath String:");

        jLabel1.setText("Name:");

        jLabel2.setText("Url:");

        jLabel3.setText("Page:");

        sourcesComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        sourcesComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sourcesComboBoxItemStateChanged(evt);
            }
        });

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Source type:");

        sourceTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        sourceTypeComboBox.setName("sourceTypeDropDown");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Set as Default");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(btnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                .addComponent(btnCancel)
                                .addGap(15, 15, 15))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(22, 22, 22)
                                .addComponent(sourcesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sourceTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(jCheckBox1))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUrl, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                    .addComponent(txtPage, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(224, 224, 224))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtQuery, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                        .addGap(224, 224, 224))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(sourcesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jLabel5)
                    .addComponent(sourceTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        if (PhotoFeed.getSelectedFeed() != oldSelected && PhotoFeed.getSelectedFeed() != null) {
            try {
            Main.LoadImage();
            }
            catch(Exception ex)
            {
                ex.printStackTrace();
            }
        }
        PhotoFeed.saveToXML();
    }//GEN-LAST:event_formComponentHidden
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        sourceTypeComboBox.removeAllItems();
        for (PhotoFeed.SourceType s: PhotoFeed.SourceType.values()) {
            
            sourceTypeComboBox.addItem(s);
        }
        sourcesComboBox.removeAllItems();
        for (PhotoFeed f: PhotoFeed.feeds) {
            sourcesComboBox.addItem(f.getName());
        }
        sourcesComboBox.addItem("Add New");
    }//GEN-LAST:event_formComponentShown
    
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.setVisible(false);
        Main.busyPanel.setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (sourcesComboBox.getSelectedItem().equals("Add New")) {
            PhotoFeed f = new PhotoFeed();
            f.setName(txtName.getText());
            f.setBaseUrl(txtUrl.getText());
            f.setPageUrl(txtPage.getText());
            f.setQueryString(txtQuery.getText());
            f.setSourceType(PhotoFeed.SourceType.valueOf((String)sourceTypeComboBox.getSelectedItem()));
            if (jCheckBox1.isSelected())
                PhotoFeed.setSelectedFeed(f);
            PhotoFeed.feeds.add(f);
        } else {
            int selectedIndex = sourcesComboBox.getSelectedIndex();
            PhotoFeed f = PhotoFeed.feeds.get(selectedIndex);
            f.setName(txtName.getText());
            f.setBaseUrl(txtUrl.getText());
            f.setPageUrl(txtPage.getText());
            f.setQueryString(txtQuery.getText());
            f.setSourceType(PhotoFeed.SourceType.valueOf(sourceTypeComboBox.getSelectedItem().toString()));
            if (jCheckBox1.isSelected())
                PhotoFeed.setSelectedFeed(f);
        }
        setVisible(false);
        Main.busyPanel.setVisible(true);
    }//GEN-LAST:event_btnSaveActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (sourcesComboBox.getSelectedItem().equals("Add New") != true) {
            PhotoFeed.feeds.remove(sourcesComboBox.getSelectedIndex());
        }
        formComponentShown(null);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void sourcesComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sourcesComboBoxItemStateChanged
        JComboBox cb = (JComboBox)evt.getSource();
        PhotoFeed selectedFeed;
        String item = (String)evt.getItem();
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            // Populate form
            for(PhotoFeed f : PhotoFeed.feeds) {
                if (f.getName().equals(item)) {
                    txtName.setText(f.getName());
                    txtUrl.setText(f.getBaseUrl());
                    txtPage.setText(f.getPageUrl());
                    txtQuery.setText(f.getQueryString());
                    sourceTypeComboBox.setSelectedItem(f.getSourceType());
                    if (PhotoFeed.getSelectedFeed() == f) {
                        jCheckBox1.setSelected(true);
                    } else { jCheckBox1.setSelected(false); }
                    break;
                }
            }
            if (item.equals("Add New")) {
                txtName.setText("");
                txtUrl.setText("");
                txtPage.setText("");
                txtQuery.setText("");
                jCheckBox1.setSelected(false);
            }
        }
    }//GEN-LAST:event_sourcesComboBoxItemStateChanged
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox sourceTypeComboBox;
    private javax.swing.JComboBox sourcesComboBox;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPage;
    private javax.swing.JTextField txtQuery;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables
    
}
