/*
 * MainPanel.java
 *
 * Created on August 21, 2006, 8:21 PM
 */

package ab5k;

import ab5k.security.DockSkinner;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.PointerInfo;
import java.awt.Rectangle;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.geom.Point2D;
import java.util.Date;
import javax.swing.Action;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SpinnerDateModel;
import javax.swing.SwingUtilities;
import javax.xml.stream.events.StartDocument;
import org.jdesktop.swingx.JXBusyLabel;
import org.jdesktop.swingx.JXButton;
import org.jdesktop.swingx.JXPanel;
import org.jdesktop.swingx.painter.CompoundPainter;
import org.jdesktop.swingx.painter.MattePainter;
import org.jdesktop.swingx.painter.Painter;
import org.jdesktop.swingx.painter.PinstripePainter;
import org.joshy.util.u;

/**
 *
 * @author  joshy
 */
public class MainPanel extends javax.swing.JPanel {
    public enum DockingSide { Left, Right };
    private DockingSide side = DockingSide.Right;
    public Core main;
    
    
    /** Creates new form MainPanel */
    public MainPanel() {
        this(null);
    }
    
    public MainPanel(Core main) {
        setMain(main);
        initComponents();
        
        
        logoButton.setText("");
        logoButton.setIcon(new ImageIcon(getClass().getResource("/images/logo 1.png")));
        
        JXButton logo = (JXButton) logoButton;
        logo.setContentAreaFilled(false);
        //GradientPaint grad = new GradientPaint(new Point(0,0), Color.GRAY, new Point(10,0), Color.WHITE);
        //MattePainter bg = new MattePainter(grad);
        //bg.setSnapPaint(true);
        
        //Painter comp = logo.getForegroundPainter();
        //CompoundPainter cp = new CompoundPainter(bg,comp);
        //logo.setForegroundPainter(cp);
        miniModePanel.setLayout(new BoxLayout(miniModePanel,BoxLayout.Y_AXIS));
        
        stripButtonLeft.addActionListener(main.getCollapseWindowAction());
        stripButtonRight.addActionListener(main.getCollapseWindowAction());
        logoButton.addActionListener(main.getCollapseWindowAction());
        
        DockSkinner.skinDock(this);
    }
    
    
    public void showGlasspane() {
        // first test of a glasspane
        JXPanel panel = new JXPanel();
        panel.setOpaque(false);
        panel.setBackgroundPainter(new PinstripePainter(Color.RED,45));
        Dimension size = new Dimension(500,500);
        panel.setSize(size);
        panel.setLocation(200,200);
        desktop.add(panel);
    }
    
    public void setMain(Core main) {
        this.main = main;
    }
    
    public Action getPreferencesAction() {
        return main.getPreferencesAction();
    }
    
    public Action getShowManageDialogAction() {
        return main.getShowManageDialogAction();
    }
    
    public Action getQuitAction() {
        return main.getQuitAction();
    }
    
    public Action getCollapseWindowAction() {
        return main.getCollapseWindowAction();
    }
    
    public DockingSide getDockingSide() {
        return this.side;
    }
    
    public void setDockingSide(DockingSide side) {
        this.side = side;
        this.remove(dockPanel);
        if(side == DockingSide.Left) {
            this.add(dockPanel,"East");
        }
        if(side == DockingSide.Right) {
            this.add(dockPanel,"West");
        }
        this.validate();
        dockPanel.validate();
        u.p("dock side set to : " + side);
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        desktop = new CustomDesktopPane();
        dockPanel = new JXPanel();
        manageButton = new javax.swing.JButton();
        collapseButton = new javax.swing.JButton();
        logoButton = new JXButton();
        quitButton = new javax.swing.JButton();
        stripButtonLeft = new javax.swing.JButton();
        stripButtonRight = new javax.swing.JButton();
        miniModePanel = new javax.swing.JPanel();
        loadingSpinner = new org.jdesktop.swingx.JXBusyLabel();

        setLayout(new java.awt.BorderLayout());

        add(desktop, java.awt.BorderLayout.CENTER);

        dockPanel.setLayout(new java.awt.GridBagLayout());

        dockPanel.setBackground(new java.awt.Color(255, 0, 51));
        dockPanel.setPreferredSize(new java.awt.Dimension(180, 500));
        manageButton.setAction(getShowManageDialogAction());
        manageButton.setText("Manage");
        manageButton.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        dockPanel.add(manageButton, gridBagConstraints);

        collapseButton.setAction(getCollapseWindowAction());
        collapseButton.setText("<");
        collapseButton.setOpaque(false);
        collapseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collapseButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        dockPanel.add(collapseButton, gridBagConstraints);

        logoButton.setBorderPainted(false);
        logoButton.setContentAreaFilled(false);
        logoButton.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        dockPanel.add(logoButton, gridBagConstraints);

        quitButton.setAction(getQuitAction());
        quitButton.setText("quit");
        quitButton.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        dockPanel.add(quitButton, gridBagConstraints);

        stripButtonLeft.setBorder(null);
        stripButtonLeft.setMinimumSize(new java.awt.Dimension(1, 1));
        stripButtonLeft.setOpaque(false);
        stripButtonLeft.setPreferredSize(new java.awt.Dimension(10, 10));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        dockPanel.add(stripButtonLeft, gridBagConstraints);

        stripButtonRight.setBorder(null);
        stripButtonRight.setMinimumSize(new java.awt.Dimension(1, 1));
        stripButtonRight.setOpaque(false);
        stripButtonRight.setPreferredSize(new java.awt.Dimension(10, 10));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        dockPanel.add(stripButtonRight, gridBagConstraints);

        miniModePanel.setLayout(new java.awt.GridLayout(20, 1));

        miniModePanel.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.weighty = 10.0;
        dockPanel.add(miniModePanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        dockPanel.add(loadingSpinner, gridBagConstraints);

        add(dockPanel, java.awt.BorderLayout.WEST);

    }// </editor-fold>//GEN-END:initComponents
    
    private void collapseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collapseButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_collapseButtonActionPerformed
    
    public int getDockWidth() {
        return dockPanel.getWidth();
    }
    
    public JPanel getDockPanel() {
        return miniModePanel;
    }
    
    public JXBusyLabel getSpinner() {
        return loadingSpinner;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton collapseButton;
    public javax.swing.JDesktopPane desktop;
    public javax.swing.JPanel dockPanel;
    private org.jdesktop.swingx.JXBusyLabel loadingSpinner;
    public javax.swing.JButton logoButton;
    private javax.swing.JButton manageButton;
    private javax.swing.JPanel miniModePanel;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton stripButtonLeft;
    private javax.swing.JButton stripButtonRight;
    // End of variables declaration//GEN-END:variables
    
    
}
