/*
 * WorldMapForm.java
 *
 * Created on February 15, 2007, 3:26 PM
 */

package worldmap;

import java.awt.Color;
import java.awt.Insets;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.JXMapViewer;
import org.jdesktop.swingx.mapviewer.DefaultWaypointRenderer;
import org.jdesktop.swingx.mapviewer.GeoPosition;
import org.jdesktop.swingx.mapviewer.Waypoint;
import org.jdesktop.swingx.mapviewer.WaypointPainter;
import org.jdesktop.swingx.mapviewer.bmng.CylindricalProjectionTileFactory;
import org.jdesktop.swingx.mapviewer.bmng.SLMapServerInfo;
import org.jdesktop.swingx.mapviewer.util.GeoUtil;
import org.jdesktop.swingx.painter.CompoundPainter;
import org.jdesktop.swingx.painter.RectanglePainter;
import org.jdesktop.swingx.painter.TextPainter;
import org.joshy.util.u;

/**
 *
 * @author  joshy
 */
public class WorldMapForm extends javax.swing.JPanel {
    WaypointPainter waypointPainter;
    /** Creates new form WorldMapForm */
    public WorldMapForm() {
        waypointPainter = new WaypointPainter();
        waypointPainter.setRenderer(new DefaultWaypointRenderer());
        
        RectanglePainter rp = new RectanglePainter(120,25,10,new Color(100,100,100,150));
        rp.setInsets(new Insets(5,0,0,0));
        rp.setVerticalAlignment(RectanglePainter.VerticalAlignment.TOP);
        final TextPainter tp = new TextPainter();
        tp.setInsets(new Insets(10,0,0,0));
        tp.setText("stuff");
        tp.setFillPaint(Color.WHITE);
        tp.setVerticalAlignment(TextPainter.VerticalAlignment.TOP);
        
        initComponents();
        /*
        kit.setTileFactory(new CylindricalProjectionTileFactory(new SLMapServerInfo(
                "file:/Users/joshy/projects/java.net/ImageTileCutter/big_tiles_26000")));
        */
        kit.getMainMap().setOverlayPainter(new CompoundPainter(waypointPainter,rp,tp));
        kit.getMainMap().addMouseMotionListener(new MouseMotionAdapter() {
            public void mouseMoved(MouseEvent e) {
                
                // get the screen point
                Point pt = e.getPoint();
                JXMapViewer map = kit.getMainMap();
                //u.p("pos = " + e.getPoint());
                // convert to world bitmap coords
                Rectangle rect = map.getViewportBounds();
                //u.p("rect = " + rect);
                pt.setLocation(rect.getX()-pt.getX(),rect.getY()-pt.getY());
                //u.p("pt = " + pt);
                // convert to geoposition
                GeoPosition gp = map.getTileFactory().pixelToGeo(pt, map.getZoom());
                u.p("gp " + gp);
                DecimalFormat fmt = new DecimalFormat("#00.000");
                tp.setText(fmt.format(gp.getLatitude()) + " , " + fmt.format(gp.getLongitude()));
                map.repaint();
            }
        });
        
        
        
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        kit = new org.jdesktop.swingx.JXMapKit();
        jPanel1 = new javax.swing.JPanel();
        query = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        query.setText("street, city, state");

        jLabel1.setText("Address:");

        jButton1.setText("Search Yahoo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(query, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jButton1)
                    .add(query, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, kit, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(kit, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if(query.getText().split(",").length < 3) {
                JOptionPane.showMessageDialog(this,"You must use the format: street, city, state");
                return;
            }
            GeoPosition gp = GeoUtil.getPositionForAddress(query.getText().split(","));
            Set<Waypoint> wps = new HashSet<Waypoint>();
            wps.add(new Waypoint(gp));
            
            waypointPainter.setWaypoints(wps);
            kit.setCenterPosition(gp);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private org.jdesktop.swingx.JXMapKit kit;
    private javax.swing.JTextField query;
    // End of variables declaration//GEN-END:variables
    
}
