/*
 * Dock.java
 *
 * Created on March 2, 2007, 8:54 PM
 */

package com.totsp.desklet.wow;

import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import org.jdesktop.swingx.JXPanel;
import org.jdesktop.swingx.painter.ImagePainter;

/**
 *
 * @author  cooper
 */
public class Dock extends JXPanel {
     BufferedImage background;
    
    /** Creates new form DockForm */
    public Dock() {
        try{
            background = ImageIO.read( getClass().getResource("/com/totsp/desklet/wow/Paper.png"));
        } catch(Exception e){
            e.printStackTrace();
        }
        this.setBackgroundPainter(new ImagePainter( background ));
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        server = new javax.swing.JLabel();

        setDoubleBuffered(false);
        setMinimumSize(new java.awt.Dimension(150, 67));

        server.setText("jLabel1");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(29, 29, 29)
                .add(server, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(24, 24, 24)
                .add(server)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel server;
    // End of variables declaration//GEN-END:variables
    
}
