/*
 * ClockDesklet.java
 *
 * Created on May 30, 2006, 4:52 PM
 */

package clockdesklet;
import java.awt.Color;
import java.awt.Font;
import java.awt.Point;
import org.jdesktop.swingx.JXPanel;
import org.jdesktop.swingx.painter.RectanglePainter;
import org.jdesktop.swingx.painter.*;
import org.jdesktop.swingx.painter.effects.ShadowPathEffect;
import org.jdesktop.swingx.util.PaintUtils;
/**
 * @author  joshy
 */
public class ClockDisplay extends JXPanel {
    
    /** Creates new form ClockDesklet */
    public ClockDisplay() {
        initComponents();
        
        try {
            currentTime.setFont(
                    Font.createFont(Font.TRUETYPE_FONT,
                        this.getClass().getResourceAsStream("Digir___.ttf")
                        ).deriveFont(Font.PLAIN,60));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //currentTime.setFont(new Font("Sanserif",Font.BOLD,12));
        
        /*
        RectanglePainter rp = new RectanglePainter(1,1,1,1, 15,15);
        rp.setFillPaint(Color.ORANGE);
        
        CompoundPainter cp = new CompoundPainter(rp, new GlossPainter());
        cp.setClipPreserved(true);
        this.setBackgroundPainter(cp);
        TextPainter text = new TextPainter();
        text.setFillPaint(Color.RED);
        ShadowPathEffect spe = new ShadowPathEffect();
        spe.setOffset(new Point(2,2));
        spe.setEffectWidth(4);
        text.setPathEffects(spe);
        currentTime.setForegroundPainter(text);*/
        try {
        Painter ptr = new URLPainter(ClockDisplay.class,"c3.xml");
        currentTime.setForegroundPainter(ptr);
        } catch (Exception ex) {
            System.out.println(ex);
            ex.printStackTrace();
        }
    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        currentTime = new org.jdesktop.swingx.JXLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 255, 0));
        setOpaque(false);
        currentTime.setBackground(new java.awt.Color(0, 255, 153));
        currentTime.setForeground(new java.awt.Color(255, 0, 0));
        currentTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentTime.setText("00:00");
        currentTime.setFont(new java.awt.Font("Lucida Grande", 0, 60));

        jButton1.setText("setup");
        jButton1.setOpaque(false);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .add(jButton1))
            .add(currentTime, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(currentTime, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public org.jdesktop.swingx.JXLabel currentTime;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
    
}
