/*
 * CalendarForm.java
 *
 * Created on February 13, 2007, 12:30 PM
 */

package calendar;

import java.awt.Color;
import java.awt.Insets;
import org.apache.batik.ext.awt.LinearGradientPaint;
import java.awt.Point;
import java.util.Date;
import org.jdesktop.swingx.JXPanel;
import org.jdesktop.swingx.painter.CompoundPainter;
import org.jdesktop.swingx.painter.PinstripePainter;
import org.jdesktop.swingx.painter.RectanglePainter;
import org.jdesktop.swingx.painter.effects.GlowPathEffect;
import org.joda.time.DateTime;

/**
 *
 * @author  joshy
 */
public class CalendarForm extends javax.swing.JPanel {
    
    private DateTime date = new DateTime();
    
    /** Creates new form CalendarForm */
    public CalendarForm() {
        initComponents();
        updateDate();
        
        RectanglePainter rect = new RectanglePainter(new Color(150,0,0), Color.BLACK);
        rect.setRounded(true);
        rect.setRoundHeight(10);
        rect.setRoundWidth(10);
        rect.setInsets(new Insets(3,3,3,3));
        rect.setStyle(RectanglePainter.Style.FILLED);
        
        
        rect = new RectanglePainter();
        rect.setBorderPaint(new Color(51,51,51));
        rect.setBorderWidth(3f);
        rect.setAreaEffects(new GlowPathEffect());
        rect.setRounded(true);
        rect.setRoundHeight(40);
        rect.setRoundWidth(40);
        
        LinearGradientPaint grad = new LinearGradientPaint(
                new Point(61,13), new Point(62,160),
                new float[] {0f, 0.33f, 0.88f, 1.0f},
                new Color[] { new Color(0,0,0), new Color(153,0,0), new Color(255,0,0), new Color(251,177,177) });
        rect.setFillPaint(grad);
        rect.setInsets(new Insets(3,3,3,3));
        rect.setPaintStretched(true);
        
        PinstripePainter pin = new PinstripePainter(new Color(204,0,0,36),45, 8, 8);
        
        CompoundPainter comp = new CompoundPainter(rect,pin);
        comp.setClipPreserved(true);
        
        
        ((JXPanel)leftPanel).setBackgroundPainter(comp);
        ((JXPanel)rightPanel).setBackgroundPainter(comp);
        
        JXPanel panel = (JXPanel)jPanel1;
        panel.setBackgroundPainter(new CompoundPainter(
                //new MattePainter(Color.WHITE),
                new MonthPainter(this)
                ));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new JXPanel();
        jPanel1 = new JXPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        month = new javax.swing.JLabel();
        rightPanel = new JXPanel();
        dayOfWeek = new javax.swing.JLabel();
        dayOfMonth = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setOpaque(false);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 237, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 174, Short.MAX_VALUE)
        );

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("<");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText(">");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        month.setForeground(new java.awt.Color(255, 255, 255));
        month.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        month.setText("Month");

        org.jdesktop.layout.GroupLayout leftPanelLayout = new org.jdesktop.layout.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(leftPanelLayout.createSequentialGroup()
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(month, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton2))
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(leftPanelLayout.createSequentialGroup()
                .add(leftPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jButton2)
                    .add(month, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(leftPanel);

        dayOfWeek.setFont(new java.awt.Font("Lucida Grande", 0, 24));
        dayOfWeek.setForeground(new java.awt.Color(255, 255, 255));
        dayOfWeek.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dayOfWeek.setText("Wednesday");

        dayOfMonth.setFont(new java.awt.Font("Lucida Grande", 0, 100));
        dayOfMonth.setForeground(new java.awt.Color(255, 255, 255));
        dayOfMonth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dayOfMonth.setText("33");

        org.jdesktop.layout.GroupLayout rightPanelLayout = new org.jdesktop.layout.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dayOfWeek, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, dayOfMonth, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(rightPanelLayout.createSequentialGroup()
                .add(dayOfWeek)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dayOfMonth, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
        );

        add(rightPanel);
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setDate(getDate().plusMonths(1));
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setDate(getDate().minusMonths(1));
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void updateDate() {
        setDate(new DateTime(new Date()));
    }
    
    public DateTime getDate() {
        return date;
    }
    
    public void setDate(DateTime date) {
        this.date = date;
        month.setText(date.monthOfYear().getAsText() + " " +
                date.year().getAsText());
        dayOfWeek.setText(date.dayOfWeek().getAsText());//dayOfWeekFormat.format(date));
        dayOfMonth.setText(date.dayOfMonth().getAsText());//dayOfMonthFormat.format(date));
        jPanel1.repaint();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dayOfMonth;
    private javax.swing.JLabel dayOfWeek;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel month;
    private javax.swing.JPanel rightPanel;
    // End of variables declaration//GEN-END:variables
    
    
    
}
